name             'charon'
maintainer       'Wanelo, Inc'
maintainer_email 'dev@wanelo.com'
license          'All rights reserved'
description      'Installs/Configures charon'
long_description 'Installs/Configures charon'
version          '0.1.3'

depends 'paths'
depends 'smf'
